# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 Huang Rui <vowstar@gmail.com>

[workspace]
resolver = "3"
members = [
    "crates/ptouch-core",
    "crates/ptouch-render",
    "crates/ptouch-cli",
    "crates/ptouch-gui",
]

[workspace.package]
version = "0.8.2"
edition = "2024"
authors = ["Huang Rui <vowstar@gmail.com>"]
license = "GPL-3.0-or-later"
repository = "https://github.com/wakuwakumiwaku/ptouch-rs-notstupid"

[profile.release]
opt-level = 2

[profile.dev.package."*"]
opt-level = 2
